export const initialState = [{
    "id": 1,
    "text": "Tabbitha"
  }, {
    "id": 2,
    "text": "Rickie"
  }, {
    "id": 3,
    "text": "Jacquelin"
  }, {
    "id": 4,
    "text": "Dorri"
  }, {
    "id": 5,
    "text": "Brigham"
  }, {
    "id": 6,
    "text": "Ajinkya"
  }, {
    "id": 7,
    "text": "Hadley"
  }, {
    "id": 8,
    "text": "Orland"
  }, {
    "id": 9,
    "text": "Fifine"
  }, {
    "id": 10,
    "text": "Trudie"
  }, {
    "id": 11,
    "text": "Henderson"
  }, {
    "id": 12,
    "text": "Korrie"
  }, {
    "id": 13,
    "text": "Letti"
  }, {
    "id": 14,
    "text": "Carny"
  }, {
    "id": 15,
    "text": "Sol"
  }, {
    "id": 16,
    "text": "Zaria"
  }, {
    "id": 17,
    "text": "Flss"
  }, {
    "id": 18,
    "text": "Preston"
  }, {
    "id": 19,
    "text": "Norman"
  }, {
    "id": 20,
    "text": "Jermain"
}]